### ISSUE TITLE
Great library to simplify the react-redux use for React projects

### ISSUE THREAD

**Issue by mcendon** [j-a-s-d/react-redux-class-helper#1]
It could be a nice to have a TS version too!!!, and to be able to install the helper class as a dependency (via NPM) instead of download the code manually. That can help too with the version management, and you could get rid off the static property VERSION inside the class.

Code is great, you may also take in consideration the using of Array.isArray() method instead of Object.prototype.toString(....) == '[object Array]'
https://github.com/j-a-s-d/react-redux-class-helper/blob/10680609b0ad2ef6e23a65a98e6a57b0dd769bd1/react-redux-class-helper.js#L18

Warm hugs friend!

**Comment by j-a-s-d** [comment]
Nice suggestions, I will take note of those, be sure!

Thanks for your comments buddy!

**Comment by mcendon** [comment]
😉💯
